[package]
name = "serial-num"
version = "0.1.1"
authors = ["Tim Wiechers <mail@timwie.dev>"]
repository = "https://github.com/timwie/serial-num"
categories = ["no-std"]
description = "Serial number type with wraparound"
keywords = ["serial", "number", "rfc-1982"]
license = "MIT OR Apache-2.0"
edition = "2021"

# MSRV is 1.60, which adds namespaced-features with "dep:" prefix
rust-version = "1.60"

# TODO: rust-version
# https://github.com/bincode-org/bincode/issues/543

[lib]
doctest = false

[dependencies.bincode]
version = "^2.0.0-rc.3"
default-features = false
features = ["derive"]
optional = true

[dependencies.serde]
version = "~1"
default-features = false
features = ["derive"]
optional = true

[features]
default = []
bincode = ["dep:bincode"]
serde = ["dep:serde"]
