[package]
name = "serial-num"
version = "0.3.1"
authors = ["Tim Wiechers <mail@timwie.dev>"]
repository = "https://github.com/timwie/serial-num"
documentation = "https://docs.rs/serial-num/"
categories = ["no-std"]
description = "Serial number type with wraparound"
keywords = ["serial", "number", "rfc-1982"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.63"
exclude = [".github/"]

[dependencies.arbitrary]
version = "~1"
features = ["derive"]
optional = true

[dependencies.bincode]
version = "^2.0.0-rc.3"
default-features = false
features = ["derive"]
optional = true

[dependencies.borsh]
version = "~0"
default-features = false
optional = true

[dependencies.rkyv]
version = "~0"
default-features = false
optional = true

[dependencies.serde]
version = "~1"
default-features = false
features = ["derive"]
optional = true

[features]
default = []
arbitrary = ["dep:arbitrary"]
bincode = ["dep:bincode"]
borsh = ["dep:borsh"]
rkyv = ["rkyv/size_32"]
rkyv-safe = ["rkyv/size_32", "rkyv/validation"]
serde = ["dep:serde"]
