[graph]
all-features = true

[licenses]
unused-allowed-license = "allow"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "0BSD",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]
