[target.'cfg(all())']
rustflags = [
    "-Dclippy::all",
    "-Dclippy::restriction",
    "-Dclippy::pedantic",
    "-Dclippy::suspicious",
    "-Dclippy::wildcard_dependencies",
    "-Delided_lifetimes_in_paths",
    "-Dlegacy_derive_helpers",
    "-Dunknown_lints",
    "-Dunused_imports",
    "-Dunused-mut",
    "-Drustdoc::bare_urls",
    "-Drustdoc::broken_intra_doc_links",
    "-Drustdoc::invalid_codeblock_attributes",
    "-Drustdoc::invalid_rust_codeblocks",
    "-Drustdoc::missing_crate_level_docs",
    "-Drustdoc::private_intra_doc_links",

    "-Wclippy::as-conversions",
    "-Wclippy::cast-possible-wrap",
    "-Wclippy::integer_arithmetic",
    "-Wclippy::missing_trait_methods",

    "-Aclippy::arithmetic_side_effects",
    "-Aclippy::blanket-clippy-restriction-lints",
    "-Aclippy::decimal-literal-representation",
    "-Aclippy::implicit-return",
    "-Aclippy::missing-docs-in-private-items",
    "-Aclippy::missing-trait-methods",
]
